### ISSUE TITLE
test(timeout) doesn't seem to work

### ISSUE THREAD

**Issue by Egorand** [cashapp/turbine#13]
See the screenshot: the tests claim that they timed out after waiting for 1000ms, but none of the test methods run for that long, most of them failing after ~20ms.

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/1186186/94202266-62387d80-fe8b-11ea-9a6c-911166d1a68c.png">

**Comment by JakeWharton** [comment]
Weird. I mean this is just a call to `withTimeout` from coroutines. There's no custom timeout implementation or anything.

**Comment by ffgiraldez** [comment]
I face the same problem, and was a flow configuration problem, I was returning a `BroadcastChannel`, instead of `ConflatedBroadcastChannel` as Flow and configuring it before consuming it via turbine

```kotlin
val channel = BroadcastChannel<String>(1) // using ConflatedBroadcastChannel test pass
given { myMock.anyMethod() } willAnswer { channel.asFlow() }
channel.send("test")

myMock.anyMethod().test {
  assertEquals(expectItem(), "test")
}

```

**Comment by JakeWharton** [comment]
I debugged the original issue as being caused by using `runBlockingTest` with a coroutine that was truly asynchronous using its own threads. `runBlockingTest` spins time as fast as possible which is why the 1000ms timeout was occurring in only 20ms. We switched to `runBlocking` which behaves as expected with coroutines that are truly asynchronous.
