### ISSUE TITLE
`StateFlow` created with `.stateIn` tests differently than `MutableStateFlow` backing variable

### ISSUE THREAD

**Issue by tommyjackson** [cashapp/turbine#204]
Given a `MutableStateFlow` backing variable and a `StateFlow` that is created from the backing variable using `.stateIn`, the testing behavior with Turbine differs (using `StandardTestDispatcher()`). The test with the backing field behaves how I would expect (and passes), but I don't want to expose the backing variable in our code, and I wouldn't expect them to behave differently regardless. Am I misunderstanding something with how `.stateIn` works, or is this an issue with Turbine?

```
class TurbineStateInTest {

    @get:Rule
    val coroutineTestRule = CoroutineTestRule(StandardTestDispatcher())

    private lateinit var backingState: MutableStateFlow<State>
    private lateinit var state: StateFlow<State>

    @Before
    fun before() {
        backingState = MutableStateFlow(State())
        state = backingState
            .stateIn(
                CoroutineScope(coroutineTestRule.dispatcher),
                SharingStarted.WhileSubscribed(5000),
                backingState.value,
            )
    }

    private suspend fun loadData() = withContext(coroutineTestRule.dispatcher) {
        backingState.emit(
            backingState.value.copy(isLoading = true)
        )

        backingState.emit(
            backingState.value.copy(isLoading = false, item = "1234")
        )
    }

    @Test // THIS TEST FAILS
    fun test() = runTest(coroutineTestRule.dispatcher) {
        state.test(timeout = Duration.INFINITE) {
            loadData()

            skipItems(1) // skip default emission

            val itemOne = awaitItem()
            assert(itemOne == expectedFirst)

            val itemTwo = awaitItem()
            assert(itemTwo == expectedSecond)
        }
    }

    @Test // THIS TEST PASSES
    fun testBackingField() = runTest(coroutineTestRule.dispatcher) {
        backingState.test(timeout = Duration.INFINITE) {
            loadData()

            skipItems(1) // skip default emission

            val itemOne = awaitItem()
            assert(itemOne == expectedFirst)

            val itemTwo = awaitItem()
            assert(itemTwo == expectedSecond)
        }
    }

    companion object {
        data class State(
            val isLoading: Boolean = false,
            val item: String? = null,
        )

        private val expectedFirst = State(isLoading = true)
        private val expectedSecond = State(isLoading = false, item = "1234")
    }
}
```

**Comment by tommyjackson** [comment]
This seems to be an issue with the conflation of `StateFlow` and not with Turbine, so I'll close this issue. Still seems weird that testing the `MutableStateFlow` works even though it should behave the same as `StateFlow` regarding conflation. ([coroutines issue](https://github.com/Kotlin/kotlinx.coroutines/issues/3143), [relevant SO post](https://stackoverflow.com/questions/73441283/testing-kotlin-flows-by-using-tolist-extension-skips-some-emissions))

**Comment by jingibus** [comment]
First, this construct:

```kotlin
    @Before
    fun before() {
        backingState = MutableStateFlow(State())
        state = backingState
            .stateIn(
                CoroutineScope(coroutineTestRule.dispatcher),
                SharingStarted.WhileSubscribed(5000),
                backingState.value,
            )
    }
```

...should be avoided. Invoking the standalone `CoroutineScope` constructor without explicitly cancelling it somewhere is an instant coroutine leak.

Consider instead writing structured concurrent code like this instead to automatically ensure coroutines are never leaked:

```kotlin
    @Test
    fun test() = runTest(coroutineTestRule.dispatcher) {
        val state = backingState.stateIn(
                this.backgroundScope,
                SharingStarted.Eagerly,
                backingState.value,
            )
        state.test(timeout = Duration.INFINITE) {
            loadData()

            skipItems(1) // skip default emission

            val itemOne = awaitItem()
            assertEquals(itemOne, expectedFirst)

            val itemTwo = awaitItem()
            assertEquals(itemTwo, expectedSecond)
        }
    }
```

Second: as you've already noted, be careful when assuming StateFlow will always run a particular way. As you said, `StateFlow` [conflates its outputs, so it can be weird](https://www.billjings.com/posts/title/testing-stateflow-is-annoying/). 

This is probably biting you here because `backingState.stateIn` is not _exactly_ identical to a bare `MutableStateFlow`. It creates an additional `MutableStateFlow` and an additional coroutine to drive values into it; I'm sure you could figure out why it is not behaving differently if you really dug into it, but I personally prefer to avoid writing test code that requires such deep wizardry to understand. Give me a plain old cold `Flow`, `Channel`, or `SharedFlow` any day of the week!
