### ISSUE TITLE
Turbine not found on gradle's default maven central url (https://repo.maven.apache.org/maven2)

### ISSUE THREAD

**Issue by dsyang** [cashapp/turbine#230]
I'm trying to pull turbine into my android app but gradle can't find find it in maven central. It seems like gradle's default maven central url is [`https://repo.maven.apache.org/maven2`](https://github.com/gradle/gradle/blob/d62830774ae867342c1b2b0e73f7575df953aa26/subprojects/core-api/src/main/java/org/gradle/api/artifacts/ArtifactRepositoryContainer.java#L52) but turbine is only uploaded at https://repo1.maven.org/maven2.

```
Execution failed for task ':records-manager:generateDebugUnitTestStubRFile'.
> Could not resolve all files for configuration ':records-manager:debugUnitTestRuntimeClasspath'.
   > Could not find app.cash.tubine:turbine:0.13.0.
     Searched in the following locations:
       - file:/Users/dsyang/project/src/mobile/android/libs/turbine-0.13.0.jar
       - file:/Users/dsyang/project/src/mobile/android/libs/turbine.jar
       - file:/Users/dsyang/.m2/repository/app/cash/tubine/turbine/0.13.0/turbine-0.13.0.pom
       - https://dl.google.com/dl/android/maven2/app/cash/tubine/turbine/0.13.0/turbine-0.13.0.pom
       - https://repo.maven.apache.org/maven2/app/cash/tubine/turbine/0.13.0/turbine-0.13.0.pom
       - https://jitpack.io/app/cash/tubine/turbine/0.13.0/turbine-0.13.0.pom
       - https://plugins.gradle.org/m2/app/cash/tubine/turbine/0.13.0/turbine-0.13.0.pom
     Required by:
         project :records-manager
  ```
  
  I have to add `maven(url = "https://repo1.maven.org/")` to my project's top level `build.gradle.kts` in order for it to work. Is this expected? 
  
  I can also repro this on a blank android studio project. 
  Gradle version: 8.0
  AS version: 2022.2.1

**Comment by JakeWharton** [comment]
This is outside our control. Sonatype controls the domains, the DNS, and the S3 bucket behind Maven Central. Gradle controls the URL which is used by the `mavenCentral()` function.

There was a problem with https://repo.maven.apache.org/maven2 a few weeks ago, but it fixed itself soon thereafter. Maybe it's happening again? I'm not sure why Gradle uses that URL instead of repo1. Maybe they can switch over time? That would be a conversation between Gradle and Sonatype though.

You can file an issue on Sonatype's JIRA issue tracker if you can reliably reproduce the problem. Unfortunately we're at their mercy.
