### ISSUE TITLE
No value was produced when testing SQLDelight with Coroutines extension

### ISSUE THREAD

**Issue by Egi10** [cashapp/turbine#274]
I conducted a Unit Test for SQLDelight, which utilizes [Coroutines extensions](https://cashapp.github.io/sqldelight/2.0.0/android_sqlite/coroutines/). An example code snippet is like this:

```
@Test
    fun `when success `() = runTest {
        insertTableA()
        insertTableB()

        dataStore.getDataById(
            id = "id"
        ).test {
            assertEquals("data", awaitItem())

            awaitComplete()
        }
    }
```

When I ran it, I encountered this error:
```
No value produced in 3s
app.cash.turbine.TurbineAssertionError: No value produced in 3s
```

Why did this happen?

**Comment by JakeWharton** [comment]
If you change `test { .. }` to `collect { println(it) }` do you see a message printed?

If you do not, then no values are being produced by your data layer and the problem is there. If there's no data then Turbine cannot ingest anything.

If you do see a message, then the problem is in Turbine. And in that case we usually can replace your data layer with a simpler flow such as `flow { emit("Hey") }` to reproduce the behavior and write a test case. But I _strongly_ suspect this isn't the case.

**Comment by Egi10** [comment]
When I use collect and add a print command, I get the message. @JakeWharton 

Everything runs smoothly without any issues if I don't use awaitComplete(), but an error occurs when awaitComplete() is added.

One example of its function is like this, using .asFlow() and .mapToList() from SQLDelight:
```
override fun getDataAWithDataB(): Flow<List<GetDataAWithDataB>> {
        val dateNow = DateTimeHelper.getCurrentISO8601UTC()
        return areaQueries.getAreasWithPondAndCultivation(
            dataNow = dateNow
        ).asFlow().mapToList(
            context = dispatcher
        )
    }
```

**Comment by JakeWharton** [comment]
SQL Delight's `Flow`s never complete. You would have to use some operator that caused the flow to complete such as `first()` or `take(Int)`. Otherwise the flow lives forever and assumes you will cancel the collection whenever you don't want to be notified about query updates.

**Comment by Egi10** [comment]
I am currently running the tests, adding .take(1) to each SQLDelight test flow. Thanks you
