### ISSUE TITLE
AdvanceTimeBy has no effect within test block when using runBlockingTest

### ISSUE THREAD

**Issue by mhernand40** [cashapp/turbine#42]
Pretty simple repro with the following test:
```Kotlin
    @Test
    fun test() = runBlockingTest {
        val flow = flow {
            delay(100L)
            emit("a")
        }

        flow.test {
            advanceTimeBy(101L)
            assertThat(expectItem()).isEqualTo("a")
        }
    }
```

However, the test above fails with the following error:
```
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at kotlinx.coroutines.test.TimedRunnable.run(TestCoroutineDispatcher.kt)
	at kotlinx.coroutines.test.TestCoroutineDispatcher.doActionsUntil(TestCoroutineDispatcher.kt:103)
	at kotlinx.coroutines.test.TestCoroutineDispatcher.advanceUntilTime(TestCoroutineDispatcher.kt:123)
	at kotlinx.coroutines.test.TestCoroutineDispatcher.advanceUntilIdle(TestCoroutineDispatcher.kt:133)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:52)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest$default(TestBuilders.kt:45)
	at com.repro.ReproTest.test(ReproTest.kt:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
```

I suspect this is probably some nuance with `TestCoroutineDispatcher` plus the fact that `test { … }` is internally using `Dispatchers.Unconfined`.

Kotlin: 1.4.31
Coroutines: 1.4.3
Turbine: 0.4.1

**Comment by ebenfield** [comment]
I guess the following is the standard usage. See this [discussion](https://app.slack.com/client/T09229ZC6/search/search-943762d0-b661-4350-bdfe-19d24349f9fa/thread/C1CFAFJSK-1617225017.293600) on slack. I think the readme could do with some more documentation.

    @Test
    fun test2() {
        val dispatcher = TestCoroutineDispatcher()
        runBlocking {
            launch(dispatcher) {
                val flow = flow {
                    delay(100L)
                    emit("a")
                }

                flow.test {
                    dispatcher.advanceTimeBy(101L)
                    kotlin.test.assertEquals("a", expectItem())
                }
            }
        }
    }
```

**Comment by JakeWharton** [comment]
@ebenfield that is standard setup for testing anything that uses delay and not at all specific to the use of this library. I'm a bit hesitant about bloating the readme with every possible variant of interaction, but perhaps now that we've added an example for sharedflow it's worth taking the time to talk about time.

**Comment by benkay** [comment]
@ebenfield's example is also broken - it both makes the test take the real-world time of the delay inside the flow { }, and also the test will pass even when removing the advanceTimeBy call

i.e. this test takes 10 seconds, and also passes
```kotlin
  @Test
  fun brokenTest() {
    val dispatcher = TestCoroutineDispatcher()
    runBlocking(dispatcher) {
      flow { delay(10_000L); emit(Unit) }
        .test {
          dispatcher.advanceTimeBy(5_000L)
          expectItem()
          expectComplete()
        }
    }
  }
```

This is because turbine ignores the current dispatcher when launching the flow, so delay() actually delays, and the test { } block _does_ run in the test dispatcher, which means expectItem's timeouts don't work

What does work is to use flowOn

```kotlin
  @Test
  fun workingTest() {
    runBlocking {
	  val dispatcher = TestCoroutineDispatcher()
      flow {
        delay(10_000L); emit(Unit)
      }
        .flowOn(dispatcher)
        .test {
          dispatcher.advanceTimeBy(11_000L)
          expectItem()
          expectComplete()
        }
    }
  }
```

Now the body of the flow is the thing running in the test dispatcher, so the delay controller works, and also so do the turbine timeouts.

IMO it would be nice if the `runBlockingTest` example was made to work somehow as it feels surprising that it doesn't.
Also the `brokenTest` example is dangerous as with short delays it's not clear that anything's wrong, and it's silently just not testing anything. Perhaps turbine should internally force the expectEvent() timeout to be 0 when using the test dispatcher?

**Comment by Antimonit** [comment]
Sadly, @benkay's example also breaks when the flow terminates with an exception. The following test:

```kotlin
@ExperimentalTime
@Test
fun `custom test`() {
    val exception = Exception("service down")
    val testDispatcher = TestCoroutineDispatcher()
    testDispatcher.runBlockingTest {
        flow<Any> { throw exception }
            .flowOn(testDispatcher)
            .test {
                Assert.assertEquals(exception, awaitError())
            }
    }
}
```
will fail with:
```
expected: java.lang.Exception<java.lang.Exception: service down> but was: java.lang.Exception<java.lang.Exception: service down>
```

The `.toString()` representation is the same but the exception returned by `awaitError()` is actually wrapping the original exception. When a custom dispatcher is used, coroutine internals at some point makes a copy of the original exception and that fails the equality assertion.

Two ways to fix this issue:
- remove the `.flowOn(testDispatcher)`,
- unwrap the exception with `awaitError().cause` but that's something no developer is going to remember to do.

---

I've decided to remove Turbine in this case, materialize the flow myself and check for items manually.

```kotlin
@ExperimentalTime
@Test
fun `custom test`() {
    val exception = Exception("service down")
    val testDispatcher = TestCoroutineDispatcher()
    val flow = flow {
        emit("1")
        delay(1000)
        emit("2")
        delay(2000)
        throw exception
    }
    testDispatcher.runBlockingTest {
        Assert.assertEquals(
            listOf(
                Event.Item("1"),
                Event.Item("2"),
                Event.Error(exception)
            ),
            flow.materialize().toList()
        )
    }
}
```

```kotlin
sealed class Event<out T> {
    data class Item<T>(val data: T) : Event<T>()
    data class Error(val throwable: Throwable) : Event<Nothing>()
    object Completion : Event<Nothing>()
}

fun <T> Flow<T>.materialize(): Flow<Event<T>> =
    map<T, Event<T>> { Event.Item(it) }
        .onCompletion { if (it == null) emit(Event.Completion) }
        .catch { emit(Event.Error(it)) }
```

Now, this is not perfect either as we have lost the ability to manually control the time via the `TestCoroutineDispatcher`. But since `testDispatcher.runBlockingTest` advances time automatically and we don't need to verify when items were emitted, this is not an issue for us.

Edit: Fix null-check in `onCompletion`
Edit2: Fix `onCompletion` and `catch` ordering

**Comment by PaulWoitaschek** [comment]
With the help of @dkhalanskyjb I found a way to make it work with the new `runTest`:

```kotlin
  suspend fun <T> Flow<T>.test2(
    timeout: Duration = 1.seconds,
    validate: suspend FlowTurbine<T>.() -> Unit,
  ) {
    val testScheduler = coroutineContext[TestCoroutineScheduler]
    return if (testScheduler == null) {
      test(timeout, validate)
    } else {
      flowOn(UnconfinedTestDispatcher(testScheduler))
        .test(timeout, validate)
    }
  }
```

Does it make sense to incoroprate this behavior direclty into turbine?

**Comment by rossdanderson** [comment]
Thanks for the hint @PaulWoitaschek - it worked for me with a small tweak - it requires a coroutineScope wrapper else it will likely import the `GlobalScope.coroutineContext` 

```kotlin
    @OptIn(ExperimentalTime::class)
    suspend fun <T> Flow<T>.test2(
        timeout: kotlin.time.Duration = 1.seconds,
        validate: suspend FlowTurbine<T>.() -> Unit,
    ) = coroutineScope {
        val testScheduler = coroutineContext[TestCoroutineScheduler]
        if (testScheduler == null) test(timeout, validate)
        else flowOn(UnconfinedTestDispatcher(testScheduler))
            .test(timeout, validate)
    }
```

**Comment by JakeWharton** [comment]
The timeout is gone on `trunk` as it is provided by `runTest` so no custom handling should be needed anymore. If you see any problems with the latest SNAPSHOT or forthcoming release please file a new issue with a reproducing test. Thanks!
