### ISSUE TITLE
assertValue/assertValues extension

### ISSUE THREAD

**Issue by 1gravity** [cashapp/turbine#61]
This is a great library. Thanks a bunch for publishing it!

I like the syntax for RxJava tests which is something like this:
```
Observable.just(1, 2, 3).test().run {
    assertValues(1, 2, 3)
}
```
It's shorter/less verbose than:
```
flowOf(1, 2, 3).test {
    assertEquals(1, awaitItem())
    assertEquals(2, awaitItem())
    assertEquals(3, awaitItem())
    awaitComplete()
}
```

By adding these two small extension functions
```
suspend fun <T> FlowTurbine<T>.assertValue(expected: T) = coroutineScope {
    assertEquals(expected, awaitItem())
}

suspend fun <T> FlowTurbine<T>.assertValues(vararg expected: T) = coroutineScope {
   for (value in expected) assertValue(value)
}
```
You could write:
```
flowOf(1, 2, 3).test {
    assertValues(1, 2, 3)
    awaitComplete()
}
```

Would you consider adding these extension functions officially to the library?

**Comment by JakeWharton** [comment]
We do not have a dependency on kotlin.test and cannot reference `assertEquals`. Moreover, one might not be using JUnit as their desired means of performing assertions (we use Truth, others use AssertJ, some use other Kotlin multiplatform libraries). Additionally, I don't think it's particularly clear that the vararg overload will wait for the specified timeout for each element rather than once for the whole set. In the most recent version we have normalized all APIs which suspend to be prefixed with `await` so as to make non-suspending methods more clear which this doesn't conform to and I'm not sure how to name them to fit. Finally, in practice, we almost never have trivial scalars on which I'm asserting but more complex model objects on which I sometimes perform partial assertion.

Because it's so easy to write these yourself as well as any other shape desired I'm inclined to not include them. I don't want to constantly be chasing all of the variants that people will inevitably want for a full assertion API. By saying "bring your own" we side-step that whole design space.

This library is deliberately designed differently than RxJava's test observer which is also why these don't fit too well. When testing RxJava things internally we actually ban the `test()` operator and use a custom one whose API more closely mirrors Turbine where you pull individual values rather than asserting on the entire received set each time.
