### ISSUE TITLE
Where to put the Gradle lines to opt-in ExperimentalTime ?

### ISSUE THREAD

**Issue by NinoDLC** [cashapp/turbine#67]
[This documentation](https://github.com/cashapp/turbine#experimental-api-usage) isn't really helpful for someone not familiar with Gradle. 

Where should I put the following lines (for an Gradle Android project) ?

https://github.com/cashapp/turbine#experimental-api-usage
```groovy
compileTestKotlin {
  kotlinOptions {
    freeCompilerArgs += [
        '-Xopt-in=kotlin.time.ExperimentalTime',
    ]
  }
}
```

**Comment by NinoDLC** [comment]
For now, I formatted my (module) build.gradle file this way : 

```
...

android {
  ...
  kotlinOptions {
      ...
      freeCompilerArgs += ['-Xopt-in=kotlin.time.ExperimentalTime']
  }
}
```

but I guess this enable the ExperimentalTime opt in for the whole module, not only during tests...

**Comment by JakeWharton** [comment]
Yes that enables it for the whole module. I'm not sure how to do only tests in an Android module.

I don't really want to be in the business of educating people how to do this because there's so many different factors which contribute to how it's done (which plugins you're using, whether you're using kts or groovy, etc.). I'm going to remove the experimental time APIs from the core and release a new version.
