### ISSUE TITLE
Upgrade to Dokka 1.4.0

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/turbine#8]
Blocked by the release plugin. Consider removing it even if we become unblocked.

**Comment by Egorand** [comment]
Removing the release plugin? Are there better alternatives?

**Comment by JakeWharton** [comment]
I've never liked it. It has far too much responsibility and has held back adoption of things like this multiple times in the past. It either needs to significantly change its architecture in order to reduce its responsibility or wiring things manually seems like a dramatically superior option.

**Comment by gabrielittner** [comment]
I will have a fix for Dokka this week. 

I completely agree that the plugin is doing too much automagically currently (like applying Dokka on it's own). I've lined out my general plan on how to evolve the plugin here https://github.com/vanniktech/gradle-maven-publish-plugin/issues/138 It evolved a bit in my head since I wrote the ticket (for example instead of a flag it will probably a separate plugin id) but it's still the general direction. I'd be very happy about feedback or if you have other ideas.
