### ISSUE TITLE
Different behaviour when using coroutines 1.6.0

### ISSUE THREAD

**Issue by alterpie** [cashapp/turbine#91]
As an example I would like to suggest following test:
```kotlin
private val stateFlow = MutableStateFlow(0)
private val flow: Flow<Int> = stateFlow

@Test
fun `turbine test`() = runBlockingTest {
    Dispatchers.setMain(TestCoroutineDispatcher())

    val scope = CoroutineScope(Job() + Dispatchers.Main)

    flow.test {
        flowOf(1, 2, 3)
            .onEach { stateFlow.value = it }
            .launchIn(scope)

        val events = cancelAndConsumeRemainingEvents()
    }

    Dispatchers.resetMain()
}
```

When using coroutines 1.5.2, as expected ```events``` variable will be a list with size of 4 which contains integers wrapped in ```Item``` class: [Item(0), Item(1), Item(2), Item(3)]

But when using coroutines 1.6.0 like so:
```kotlin
private val stateFlow = MutableStateFlow(0)
private val flow: Flow<Int> = stateFlow

@Test
fun `turbine test`() = runTest {
    Dispatchers.setMain(UnconfinedTestDispatcher())

    val scope = CoroutineScope(Job() + Dispatchers.Main)

    flow.test {
        flowOf(1, 2, 3)
            .onEach { stateFlow.value = it }
            .launchIn(scope)

        val events = cancelAndConsumeRemainingEvents()
    }

    Dispatchers.resetMain()
}
```

```events``` will contain only the first and last items: [Item(0), Item(3)].

Also if I use ```StandardTestDispatcher``` instead of ```UnconfinedTestDispatcher```, ```events``` will contain only the first item: [Item(0)].

Is it expected behaviour? Do I need to adjust my test somehow to get the same results as for coroutines version 1.5.2?

**Comment by mhernand40** [comment]
By calling `runTest` before calling `Dispatchers.setMain(UnconfinedTestDispatcher())`, it will default to `StandardTestDispatcher`. Normally `Dispatchers.setMain(…)` should be called in a `@Before` function and `Dispatchers.resetMain()` should be called in an `@After` function.

Example:
```Kotlin
@Before
fun setup() {
    Dispatchers.setMain(UnconfinedTestDispatcher())
}

@After
fun tearDown() {
    Dispatchers.resetMain()
}

@Test
fun test = runTest { // Will inherit UnconfinedTestDispatcher
    …
}
```

Based on the snippet provided in the issue summary, the `runTest` is actually using `StandardTestDispatcher` implicitly. When setting a `MutableStateFlow's` `value` while using `StandardTestDispatcher`, it is important to call either `runCurrent()`, `advanceUntilIdle()`, or `yield()` immediately afterward; otherwise the repeated `value` assignments get conflated. This might explain why you are only seeing the first value and the last value.

**Comment by alterpie** [comment]
Thank you for your reply @mhernand40 but I see only the first and the last values in case I use ```UnconfinedTestDispatcher```, not the ```StandardTestDispatcher```. Also it does not matter if I use  ```Dispatchers.setMain``` inside the test or using ```@Before``` function - the result is the same, I receive only the first and the last emission. You can see that I don't use scope provided by ```runTest```, I create a scope manually using ```Job() + Dispatchers.Main``` and at the time of creating this scope ```Dispatchers.Main``` is already substituted with ```UnconfinedTestDispatcher```.

**Comment by mhernand40** [comment]
My apologies @alterpie, I am still getting familiar with the new `runTest` API 🙂. I just ran this test locally myself and can confirm what you are seeing where only the first and last value are printed.

One thing to note is that both `runBlockingTest` and `TestCoroutineDispatcher` are still supported in version `1.6.0` although they are deprecated. FWIW I can confirm that if I run the first test snippet, the one with `runBlockingTest` and `TestCoroutineDispatcher`, with Coroutines `1.6.0`, all items `0..3` are indeed printed. Even `runTest` but with `Dispatchers.setMain(TestCoroutineDispatcher())` produces all items `0..3`. I think the major difference here is the deprecated ~`TestCoroutineDispatcher`~ vs. `UnconfinedTestDispatcher`.

**Comment by mhernand40** [comment]
Some more findings on my part. Let's use the `1.6.0` snippet, but instead of using `onEach` + `launchIn`, let's use regular `collect` + `launch`.

```Kotlin
@Test
fun `turbine test`() = runTest {
    Dispatchers.setMain(UnconfinedTestDispatcher())

    val scope = CoroutineScope(Job() + Dispatchers.Main)

    flow.test {
        scope.launch {
            flowOf(1, 2, 3).collect {
                stateFlow.value = it
            }
        }

        val events = cancelAndConsumeRemainingEvents()
    }

    Dispatchers.resetMain()
}
```

The above is logically equivalent to the `onEach` + `launchIn` approach. One thing to note is that `launch` defaults to `start = CoroutineStart.DEFAULT`. If we update the code to explicitly use `start = CoroutineStart.UNDISPATCHED`, all items `0..3` are produced.
```Kotlin
    @Test
    fun `turbine test`() = runTest {
        Dispatchers.setMain(UnconfinedTestDispatcher())

        val scope = CoroutineScope(Job() + Dispatchers.Main)

        flow.test {
            scope.launch(start = CoroutineStart.UNDISPATCHED) {
                flowOf(1, 2, 3).collect {
                    stateFlow.value = it
                }
            }

            val events = cancelAndConsumeRemainingEvents()
        }

        Dispatchers.resetMain()
    }
```

Not saying I fully understand the reason for the "different behavior" yet, but figured I'd add my findings. 🤷‍♂️

**Comment by fargus9** [comment]
Won't the timeout in `test` fire immediately with the `UconfinedTestDispatcher`?

**Comment by JakeWharton** [comment]
The timeout is gone on `trunk` as it is now provided by `runTest` automatically.

**Comment by JakeWharton** [comment]
The test in the original issue description passes on `trunk`. If you have problems with the latest SNAPSHOT and the forthcoming release please open a new issue with a similar test case example. Thanks!

**Comment by alterpie** [comment]
thank you @JakeWharton, much appreciation for your work 🙏
